language: scala
dist: trusty

scala:
  - 2.12.8

jdk:
  - openjdk8
  - openjdk11

before_script:
  # default $SBT_OPTS is irrelevant to sbt launcher
  - unset SBT_OPTS
  - chmod +x ./bin/build

script:
  - ./bin/build --no-test --dry-run --all
