name: release

# Publishes twitter/util, twitter/scrooge, twitter/finagle, twitter/twitter-server,
# and twitter/finatra.
#
# Expects a repository dispatch event: https://developer.github.com/v3/repos/#create-a-repository-dispatch-event
# in the form of JSON data POST to /repos/twitter/dodo/dispatches:
#
# {
#  "event_type": "release",
#  "client_payload": {
#    "phab_id": "D12345",
#    "version": "17.12.0",
#    "scrooge_sbt_plugin": true,
#    "scrooge_maven_plugin": true,
#    "dry_run": true
#  }
# }
env:
  JAVA_OPTS: "-Dsbt.log.noformat=true"
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
  API_KEY: ${{ secrets.API_KEY }}
defaults:
  run:
    shell: bash
on:
  repository_dispatch:
    types: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: dump/context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: openjdk@1.8
      - uses: olafurpg/setup-gpg@v2
      - name: setup/maven
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: '[{ "id": "sonatype-nexus-staging", "username": "${{ secrets.SONATYPE_USERNAME }}", "password": "${{ secrets.SONATYPE_PASSWORD }}" }, {"id": "sonatype-nexus-snapshots", "username": "${{ secrets.SONATYPE_USERNAME }}", "password": "${{ secrets.SONATYPE_PASSWORD }}" }]'
      - name: setup/sbt
        run: |
          mkdir -p ~/.sbt/1.0/plugins
          echo 'resolvers += Classpaths.sbtPluginReleases' > ~/.sbt/1.0/plugins/gpg.sbt
          echo 'addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.0.0")' >> ~/.sbt/1.0/plugins/gpg.sbt
      # checkout util and release
      - name: checkout/util
        uses: actions/checkout@v2
        with:
          repository: twitter/util
          ref: master
          path: util
      - name: release/util
        run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
          ${{ github.workspace }}/bin/publish --phab-id ${{ github.event.client_payload.phab_id }} --version ${{ github.event.client_payload.version }} --dry-run ${{ github.event.client_payload.dry_run }} --verbose util
        working-directory: ${{ github.workspace }}/util
      # checkout scrooge and release
      - name: checkout/scrooge
        uses: actions/checkout@v2
        with:
          repository: twitter/scrooge
          ref: master
          path: scrooge
      - name: release/scrooge
        run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
          ${{ github.workspace }}/bin/publish --phab-id ${{ github.event.client_payload.phab_id }} --version ${{ github.event.client_payload.version }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose scrooge
        working-directory: ${{ github.workspace }}/scrooge
      # scrooge-sbt-plugin
      - name: release/scrooge-sbt-plugin
        if: ${{ github.event.client_playload.scrooge_sbt_plugin }}
        run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
          ${{ github.workspace }}/bin/publish --phab-id ${{ github.event.client_payload.phab_id }} --version ${{ github.event.client_payload.version }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose scrooge-sbt-plugin
        working-directory: ${{ github.workspace }}/scrooge
      # scrooge-maven-plugin
      - name: release/scrooge-maven-plugin
        if: ${{ github.event.client_playload.scrooge_maven_plugin }}
        run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
          ${{ github.workspace }}/bin/publish --phab-id ${{ github.event.client_payload.phab_id }} --version ${{ github.event.client_payload.version }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose scrooge-maven-plugin
        working-directory: ${{ github.workspace }}/scrooge
      # checkout finagle and release
      - name: checkout/finagle
        uses: actions/checkout@v2
        with:
          repository: twitter/finagle
          ref: master
          path: finagle
      - name: release/finagle
        run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
          ${{ github.workspace }}/bin/publish --phab-id ${{ github.event.client_payload.phab_id }} --version ${{ github.event.client_payload.version }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose finagle
        working-directory: ${{ github.workspace }}/finagle
      # checkout twitter-server and release
      - name: checkout/twitter-server
        uses: actions/checkout@v2
        with:
          repository: twitter/twitter-server
          ref: master
          path: twitter-server
      - name: release/twitter-server
        run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
          ${{ github.workspace }}/bin/publish --phab-id ${{ github.event.client_payload.phab_id }} --version ${{ github.event.client_payload.version }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose twitter-server
        working-directory: ${{ github.workspace }}/twitter-server
      # checkout finatra and release
      - name: checkout/finatra
        uses: actions/checkout@v2
        with:
          repository: twitter/finatra
          ref: master
          path: finatra
      - name: release/finatra
        run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
          ${{ github.workspace }}/bin/publish --phab-id ${{ github.event.client_payload.phab_id }} --version ${{ github.event.client_payload.version }}  --dry-run ${{ github.event.client_payload.dry_run }} --verbose finatra
        working-directory: ${{ github.workspace }}/finatra
